### ISSUE TITLE
Kotinäyttö -> Tools-kansio

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#10]
Kotinäytöllä olevassa Tools-kansisossa (joka muuten myöskin englanniksi) on tietyt sovellukset englanniksi.
-Mi Account, Recorder, Mi Remote
![screenshot_2017-04-09-14-18-40-225_com miui home](https://cloud.githubusercontent.com/assets/16348370/24836849/b45a40bc-1d2f-11e7-9146-e8c210fbd654.png)

**Comment by dogiex** [comment]
Kohdat ovat jo käännettynä. Weekly versio nähtävästi korvannut ne englannilla.
