### ISSUE TITLE
Puhelin-sovellus

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#13]
Kun soittaa johonkin numeroon ja ei saa yhteyttä tai numerosta ei vastata, niin puhelinnumeron tiedoissa lukee Juuri Nyt Didnt Connect. Tämä  ongelma laitteissa Redmi 4 Prime sekä Mi5 Prime.
![screenshot_2017-04-11-12-07-26-165_com android contacts](https://cloud.githubusercontent.com/assets/16348370/24901598/42d70cfe-1eb0-11e7-9bf0-3a45938fd2df.png)

**Comment by dogiex** [comment]
Korjattu
