### ISSUE TITLE
Puhelin-sovellus -> Copy-teksti englanniksi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#14]
Jos puhelin sovelluksessa avaa numeron, niin copy teksti on englanniksi. tämä ongelma on laitteissa redmi 4 prime sekä mi5 prime. 
![screenshot_2017-04-11-12-07-33-620_com android contacts](https://cloud.githubusercontent.com/assets/16348370/24901635/63bb3e5e-1eb0-11e7-9bc7-5bd05a379f16.png)

**Comment by dogiex** [comment]
Korjattu
