### ISSUE TITLE
com.android.camera -> Anti Banding kohta englanniksi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#17]
Kamera-sovelluksessa kohta Anti Banding on englanniksi, yritin tuota selvittää, tuo liittyy kameran välkkymiseen jos kuvaa jotain monitoria tai tv:tä.. eli tuo liittyy välkynnänestoon? siihen keksiä joku järkevä sana? Välkynnänesto esim? tai jos sulla tulee jotain parempaa mieleen?
![screenshot_2017-04-11-19-43-57-151_com android camera](https://cloud.githubusercontent.com/assets/16348370/24920878/8888f1fe-1ef1-11e7-81c7-462a8a32de6b.png)

**Comment by dogiex** [comment]
Joo se liittyy välkynnänestoon mutta sille ei oikein löytynyt suomeksi mitään niin jätin sen Anti banding sanaksi kun sille ei oikein sanastoa löytynyt valokuvaamisesta

**Comment by dogiex** [comment]
Jätän tämän virheen avoimeksi, jotta siitä voi keskustella, kun en itse keksi mitään parempaa, kuin jättää se sanaksi Anti banding. Vai onko @Vihru sinulla parempi vaihtoehto sille? :)

**Comment by Vihru** [comment]
no onhan se kyllä hankala löytää.. mutta kyllä sille joku suomenkielinenki sana varmasti on olemassa..

**Comment by Vihru** [comment]
päivitystaajuus? koska tutkin xda developerdösia ja siel puhuttiik tuosta, siinähån on joko 50 tai 60 khz mikä liittyy kuvsn päivitykseen ja sillå saadaan estettyä se välkyntä

**Comment by Vihru** [comment]
sori kirjotin nopeesti..

**Comment by dogiex** [comment]
Hmm joo pitää tutkia tota. Joo ei se mitään, osasin tulkata oikein. :)

**Comment by Vihru** [comment]
XDA foorumilla siitä oli jotai puhetta.. puhuttii just refresh ratesta jne.. tuo hertsimäärähän jollai tavalla liittyy kuvan päivittymiseen..

**Comment by dogiex** [comment]
Joo liittyy kuvan päivittymiseen / vilkkumisen estoon.

**Comment by dogiex** [comment]
Anti Banding -sanalle ei ole suoraan suomennosta, vaan käytetään ammattitermiä sen sijaan.
