### ISSUE TITLE
com.android.settings -> keyboard and input methods

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#24]
![screenshot_2017-05-05-12-07-07-243_com android settings](https://cloud.githubusercontent.com/assets/16348370/25739818/32d621ac-318c-11e7-9449-6d8979bb676a.png)

keyboard and input methods sekä niiden alavalikot myös englanniksi.. 
Mi5 sekä uusin weekly käytössä.

**Comment by dogiex** [comment]
Kiitos virheraporteista, vastaisuudessa kerro weekly rom versio myös, helpompi kuin "uusin". Korjailen virheet, kun omilta asioilta kerkeän. :)

**Comment by Vihru** [comment]
Juu, teen jatkossa niin! kiitos.

**Comment by dogiex** [comment]
@Vihru voitko laittaa kuvakaappaukset myös niistä alavalikoista, jotta osaan etsiä oikeat tekstit?
Itselläni, kun ei ole kyseistä ominaisuutta laitteissani. Kiitos. :)

**Comment by Vihru** [comment]
tässä pyytämäsi 
![screenshot_2017-05-07-16-53-25-208_com android settings](https://cloud.githubusercontent.com/assets/16348370/25781724/d5a26f7a-3345-11e7-8bc9-0cc5a942d44c.png)
![screenshot_2017-05-07-16-53-20-196_com android settings](https://cloud.githubusercontent.com/assets/16348370/25781728/dfcdb428-3345-11e7-949b-3d6e914653f0.png)

**Comment by dogiex** [comment]
Mitäs tuon Keyboard shortcuts helper alavalikosta löytyy?

**Comment by Vihru** [comment]
se ei mene sinne.. en pääse ollenkaan. vaik laittasin virtuaalinäppiksen päälle jne..
