### ISSUE TITLE
com.miui.gallery -> kuvanmuokkaus ->  viielä

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#25]
weekly 7.5.4 ja redmi 4 pro. kirjotusvirhe varmaa.. ku lukee viielä. kuvaa muokattaessa.
![img_20170507_162040](https://cloud.githubusercontent.com/assets/16348370/25781344/abeec416-3341-11e7-8f00-2eee7f3ed66e.jpg)

**Comment by Vihru** [comment]
sähän oot ihan liekeissä nyt.. :) hieno homma. enkä mä enempää puske ilmotuksia.

**Comment by dogiex** [comment]
Anna tulla vaan kaikki virheet, mitä vaan huomaat ja jaksat ilmoittaa. :)
