### ISSUE TITLE
com.miui.home -> tools-kansio

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#26]
Weekly 7.5.4 . Kansio työpöydällä nimeltään Tools.
![img_20170507_170047](https://cloud.githubusercontent.com/assets/16348370/25781806/f4a70da8-3346-11e7-9f8b-fd35ffbdfba4.jpg)

**Comment by dogiex** [comment]
Korjattu aiemmin jo tänään.
