### ISSUE TITLE
com.miui.securitycenter > virus skanneri

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#27]
Weekly 7.5.4 ja laite Mi5. Virus skannerin voisi kirjottaa yhteen?
![img_20170507_171353](https://cloud.githubusercontent.com/assets/16348370/25781919/d2a9f74a-3348-11e7-8b9b-0fb31db62298.jpg)

**Comment by dogiex** [comment]
Vai pitäisikö se nimetä Virustarkistus?

**Comment by Vihru** [comment]
joo sekin on hyvå!
