### ISSUE TITLE
com.miui.securitycenter > akun säästäjä

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#28]
Weekly 7.5.4, laite Mi5. Olisiko fiksumpi muuttaa tuo akun säästäjä sana virransäästöksi? siitähän siinä on kai kuitenkin kyse?  tämä vain minun mielipide.. 
![screenshot_2017-05-07-17-14-11-674_com miui securitycenter](https://cloud.githubusercontent.com/assets/16348370/25781929/11f84140-3349-11e7-98f3-6a19c3d6df15.png)
![img_20170507_171830](https://cloud.githubusercontent.com/assets/16348370/25781936/36d83d8a-3349-11e7-9b0f-8d743176c7b8.jpg)

**Comment by dogiex** [comment]
Eli sana Akun säästäjä muutettaisiin Virransäästäjä sanaksi?

**Comment by Vihru** [comment]
joo esimerkiksi.. virransäästäjä tai virransäästö.. minun mielestä se olisi selkeämpi kun akun säästäjä. tietydsti myös mielipideasioita.. mutta jos ottaa muista mallia vähän.
