### ISSUE TITLE
Sää ilmoitusvalikossa

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#3]
![image](https://cloud.githubusercontent.com/assets/24968370/21737739/a0d84668-d484-11e6-8be0-ae4cc7b988e2.png)

Ilmoitusvalikossa säätyypin perässä aina > merkki
ei esiinny englanniksi

Redmi 4 Prime 7.1.5

**Comment by dogiex** [comment]
Ongelma korjattu seuraavaan versioon. Kiitos palautteesta! 👍
