### ISSUE TITLE
com.miui.securitycenter > ajasta

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#30]
Weekly 7.5.4 ja laite Mi5. Olisiko Ajastin fiksumpi muoto? entä tuo syväpuhdista teksti? esim syväpuhdistus? tai entä kun on puhdistaja niin se voisi olla myös siivoija? ja kun on sana puhdista niin sehän on aika sama kun poista.. oletko näitä miettiny sen syvällisemmin että mitkä olis helpommin ymmärettävissä.. 
![img_20170507_172657](https://cloud.githubusercontent.com/assets/16348370/25782010/b25eea34-334a-11e7-86a0-185fe743f2d9.jpg)

**Comment by dogiex** [comment]
Mietin aluksi kumpaa rupean käyttämään, Siivoaja vai Puhdistaja ja päädyin Puhdistajaan.

Noi puhdista tekstit on englanniksi Clean, ja siinä olen kanssa käyttänyt järjestelmän laajuisesti samaa sanaa, helpottaa huomattavasti kääntämistä, kun samat sanat kääntää myös samalla tavalla, eikä esimerkiksi toisessa paikassa se on Puhdista ja toisessa paikassa Poista.

Tosin jos englanniksi se on Delete niin olen kääntänyt sen Poistamiseksi tietenkin.

**Comment by dogiex** [comment]
Ja samaa metodia olen käyttänyt myös Deep Clean sanalle Syväpuhdista.

**Comment by Vihru** [comment]
juu.. no se on varmaan sit selkeä tuollain.. mietin vaan että ku on puhdistaja.. että olisko deep clean syväpuhdistus tai syväpuhdistaja jne.. mut tuo virus skanneri akun säästäjä vois olla hyviä vähä muuttaa..

**Comment by dogiex** [comment]
Mutta siinä vaiheessa, kun englannin kielen käännös teksteille vaihtuu, vaihdan niitä myös vastaamaan suomea, jota tapahtuu myös aika ajoin.

**Comment by dogiex** [comment]
Syväpuhdistaja on jo olemassa kyllä :)
