### ISSUE TITLE
com.miui.securitycenter -> estolista

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#32]
Weekly 7.5.11, testattu Mi5:lla sekä Redmi 4 Prolla.
Kun menet tietoturvaan --> estolista niin siellä englanniksi asiat.. ja kun klikkaat estolistan asetuksia niin siellä myös englanniksi kaikki.
![com miui securitycenter](https://cloud.githubusercontent.com/assets/16348370/26022721/cb9827ae-37b4-11e7-89ea-8a92ec850bcb.png)
![screenshot_2017-05-13-08-17-42-331_com miui securitycenter](https://cloud.githubusercontent.com/assets/16348370/26022722/d028f1a4-37b4-11e7-8a07-1bbf1a7e2a3d.png)

**Comment by dogiex** [comment]
Korjattu versiossa 7.5.18
