### ISSUE TITLE
com.android.phone -> palveluntarjoaja

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#33]
Weekly 7.5.11 ja laitteena redmi 4 pro sekä Mi5.  kohta your carrier.
![img_20170515_101635](https://cloud.githubusercontent.com/assets/16348370/26046877/a87b943a-3959-11e7-924e-869e51b2518c.jpg)

**Comment by dogiex** [comment]
Korjattu versiossa 7.5.18
