### ISSUE TITLE
com.android.quicksearchbox -> other ja app version

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#34]
weekly 7.5.11, laitteena redmi 4 pro sekä mi5.
![img_20170515_101656](https://cloud.githubusercontent.com/assets/16348370/26046944/e0cd981a-3959-11e7-9114-c89b3c683c43.jpg)

**Comment by dogiex** [comment]
Korjattu versiossa 7.5.18
