### ISSUE TITLE
com.android.thememanager

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#35]
weekly 7.5.11, laitteena redmi 4 pro sekä mi5.
koko teemat ilmeisesti englanniksi.
![img_20170515_101715](https://cloud.githubusercontent.com/assets/16348370/26046971/019f9642-395a-11e7-9fdb-ea7bca85a2aa.jpg)

**Comment by dogiex** [comment]
Teemasovellus jossain vaiheessa päivittyi ja sen jälkeen nuo ovat pysyneet englanniksi. Koitan katsoa, joko niille olisi tullut uudet käännettävät kohdat.

Tuo vasen ylänurkka, josta pääsee hallitsemaan teemaa on kuitenkin käännettynä?

**Comment by Vihru** [comment]
juu vasen ylänurkka on käännetty..

**Comment by dogiex** [comment]
Hyvä, silloin siis on vain puuttuvia käännöksiä eikä buildaamisessa virhettä. :)

**Comment by dogiex** [comment]
Tarkasteltuani englanninkielistä käännöspohjaa en löytänyt ylävalikon tekstejä sieltä ollenkaan eli niitä ei voi tällä hetkellä kääntää suomeksi vielä.

**Comment by Vihru** [comment]
pitäiskö sanoo siitä inbryzlle?

**Comment by dogiex** [comment]
Perusversio Teemat-sovelluksesta toimii ja on käännettynä, mutta ongelmana on se kun se päivittyy uuteen ja siinä ei ole vielä käännöksiä edes englanniksi. Huomaat sen kun käyt nollaamassa sovellustiedot Asetukset -> Asennetut sovellukset -> Teemat sovellus ja tyhjennät sovellustiedot ja käynnistät sen jälkeen Teemat-sovelluksen uudelleen niin se pyytää hyväksymään käyttöehdot ja silloin sovellus päivittää ylävalikon. Näin on ennenkin käynyt ja tietyn ajan päästä nämä on pystytty kääntämään.
Tosin voihan siitä kertoa hänelle. Eihän tuo satu. :)

**Comment by Vihru** [comment]
no eipä tuo nyt pahimmasta päästä oleva ongelma ole.. hyvä että saat muita "virheitä" korjattua kuitenkin.. uutta weeklyä innolla odottaen..

**Comment by dogiex** [comment]
Onhan tuo jo aika kauan ollut, pitää toivoa, että kohta sen voisi kääntää ja voisi siitä mainita eteenpäin kyllä.

**Comment by dogiex** [comment]
@ingbrzy Theme App gets updated when connected to internet and when agreed to terms of use, is there a way to translate this updated Theme App?

**Comment by ingbrzy** [comment]
all content is downloaded from online xiaomi servers.. so using translation from there..

**Comment by dogiex** [comment]
Ok, thank you.

**Comment by dogiex** [comment]
@Vihru eli jäljellä olevaa sisältöä ei voi kääntää, kun ne haetaan xiaomin palvelimilta suoraan.

**Comment by Vihru** [comment]
@dogiex juu ymmärsin kans, ei se mitään.. tän voi siis sulkea toisin sanoen? :)
