### ISSUE TITLE
com.duokan.phone.remotecontroller

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#36]
weekly 7.5.11, laitteena redmi 4 pro sekä mi5. Mi Remote kokonaan englanniksi?
![img_20170515_101733](https://cloud.githubusercontent.com/assets/16348370/26047003/1e3b9dc8-395a-11e7-8508-d389fc326d45.jpg)

**Comment by dogiex** [comment]
Mi Remote on käännetty kokonaan jo suomeksi, joten käännöksessä ei ole ongelmaa.
@ingbrzy could you check Mi Remote is in English even when it is completely translated to Finnish (suomi)?

**Comment by Vihru** [comment]
Juu, sen oikeestaan tiesinkin mutta tätä kautta varmaan parempi se saada myöskin inbrzyn tietoon..  sama juttu noissa muissakin, oot varmasti osan kääntänyt jo.. mutta joku mennyt buildissa pieleen..

**Comment by Vihru** [comment]
tässä uudemmassa weeklyssä myös sama ongelma

**Comment by dogiex** [comment]
Juu näyttää olevan.

**Comment by dogiex** [comment]
Ongelma jatkuu weekly 7.6.8

**Comment by dogiex** [comment]
@ingbrzy Could you please check why Mi Remote is not getting Finnish (suomi) translations?
It is translated completely.

**Comment by Vihru** [comment]
tämä ongelma vieläkin, weekly 7.6.15 ja laitteena Mi6 (sagit).

**Comment by Vihru** [comment]
@dogiex tämä ongelma myös vielä.. tässä varmaan vielä mahdollisuus saada suomeksi?

**Comment by dogiex** [comment]
Ymmärtääkseni on, koska muilla kielillä toimii.

**Comment by dogiex** [comment]
@ingbrzy Mi Remote app is still fully in English although it is translated to Finnish (suomi) already.

**Comment by Vihru** [comment]
@ingbrzy this problem exist still in weekly 7.6.29 and device Mi6 (sagit)

**Comment by Vihru** [comment]
tämä edelleen mi6 laitteessa, weeklynä 7.7.20..

**Comment by dogiex** [comment]
Viimeinen MIUI 8 versio oli 7.7.20.
Tämän johdosta tämä käännösprojekti jääköön unholaan ja tulkoon uusi projekti MIUI 9!
Uuden projektisivun löydät:

https://github.com/dogiex/MA-XML-9.0-FINNISH
