### ISSUE TITLE
com.miui.fm

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#37]
weekly 7.5.11, laitteena redmi 4 pro sekä mi5. FM-radio kokonaan englanniksi?
![img_20170515_101749](https://cloud.githubusercontent.com/assets/16348370/26047042/4a0b5722-395a-11e7-903f-eb6af5d5abfd.jpg)

**Comment by dogiex** [comment]
FM radiota ei ole vielä aloitettu kääntämään.

**Comment by Vihru** [comment]
okei, en sitä käytä mutta tein tuollaisen katsauksen taas että mistä löytyy englantia.. :)
