### ISSUE TITLE
com.android.updater -> osa englanniksi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#38]
weekly 7.5.11, laitteena redmi 4 pro sekä mi5. esim. checking englanniksi.
Cant connect  to the network, connect to wifi , retry, tuollaiset englanniksi. 
![img_20170515_101813](https://cloud.githubusercontent.com/assets/16348370/26047121/9c308e1e-395a-11e7-9c6a-2a13387f2810.jpg)

**Comment by dogiex** [comment]
Käännän updater sovelluksen loppuun varmaan viimeisien joukossa, koska OTA-päivitykset eivät enää ole käytössä, joten valikko on lähes ainoa, joka käännettynä.

**Comment by Vihru** [comment]
juu.. :)
