### ISSUE TITLE
Lukituskuvion piirto, englantia löytyi vielä

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#4]
Draw your unlock pattern
Redmi 4 Prime 7.1.5
![image](https://cloud.githubusercontent.com/assets/24968370/21737841/88d740f4-d485-11e6-947b-95ddd0cd9334.png)

**Comment by dogiex** [comment]
Käännös korjattu seuraavaan versioon.
