### ISSUE TITLE
com.miui.weather2 -> tuuli mph

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#41]
weekly 7.5.25 ja laitteena mi6. sää-sovelluksessa tuulen nopeus on mph..
![com miui weather2](https://cloud.githubusercontent.com/assets/16348370/26498325/5a7c6e8a-4237-11e7-95ce-6433ab215ce0.jpg)

**Comment by dogiex** [comment]
Sen voi muuttaa asetuksista

**Comment by Vihru** [comment]
siellä on ennen ollu kmh ja ms/s.. nyt mph ja kmh..

**Comment by Vihru** [comment]
siis m/s ja kmh..

**Comment by dogiex** [comment]
Pitäisi siellä olla 5 vaihtoehtoa tuulen nopeudelle.

- Boforiasteikko
- Kilometriä tunnissa (km/h)
- Metriä sekunnissa (m/s)
- Mailia tunnissa (mph)
- Solmua (kn)

**Comment by Vihru** [comment]
![screenshot_2017-05-26-20-20-20-491_com miui weather2](https://cloud.githubusercontent.com/assets/16348370/26505320/f7ff206c-4250-11e7-843b-fca904e437c7.png)

juu mutta ei jostain syystä ole..

**Comment by dogiex** [comment]
Kiitos kuvasta, pitääpi tutkia.

**Comment by dogiex** [comment]
Jos laitat englanninkielen päälle niin onko silti vain noi kaksi vaihtoehtoa?

**Comment by Vihru** [comment]
joo silti vain nuo kaksi vaihtoehtoa.. eli buildissa jotain?

**Comment by dogiex** [comment]
Taitaapi olla sun buildissa vielä vanha sääsovellus käytössä. Ainakin ulkoasu näyttäisi siltä.

**Comment by Vihru** [comment]
Mistäs se johtuu? Kuitenkin Mi6 puhelin joka vasta julkastu :D laita ingbryzlle ne issuet joille et voi sä tehdä mitään ni saadaan kuntoon... tää käy sulle varmaan jo ihan työstä ku kokoajan tulee issueita. mut toisaalta mulla vaihtu puhelin ni se se yks syy miks tuli taas issueita.

**Comment by dogiex** [comment]
Se taitaa johtua siitä, kun Xiaomi.eu:n omia säädöksiä ei olla vielä keretty taikoa uuteen malliin. Kyllä ne sieltä tulee, kun kerkiävät koodailla.
Issuet on tervetulleita, sen takia tämä onkin juuri se oikea paikka näille.
Täältä näen sitten, kuinka paljon olen missannut käännettävää. :)
Katsotaan nyt tässä pari weeklyä eteenpäin ja myös kun itse saan käännökset tähän 7.5.25 weeklyyn asti kiinni.

**Comment by Vihru** [comment]
tämä on kunnossa uudessa weeklyssä joten voi sulkea minun puolesta.
