### ISSUE TITLE
muistio -> recover notes

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#42]
weekly 7.5.25 ja laitteena mi6, 
![img_20170526_172325](https://cloud.githubusercontent.com/assets/16348370/26498578/2db12b74-4238-11e7-9f5e-76c9a273da85.jpg)

**Comment by dogiex** [comment]
Vieläkö ongelma jatkuu weekly 7.6.8?

**Comment by Vihru** [comment]
nopean poistamisen alapuolella on teksti: poista muistiot pilvestä.. eli tuota ongelmaa ei näytä olevan nyt ainakaan? minun puolesta voi siis ongelman sulkea.
