### ISSUE TITLE
asetukset -> lisäasetukset -> esteettömyys

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#43]
weekly 7.5.25 ja laitteena mi6. 
![img_20170526_172226](https://cloud.githubusercontent.com/assets/16348370/26498615/4815fa4e-4238-11e7-85e7-22956669c2ad.jpg)

muutamia kohtia englanniksi..

**Comment by Vihru** [comment]
nääki mun mielestä jo käännettynä ni mitä on sit oikein tapahtunut..

**Comment by dogiex** [comment]
Uusissa weeklyissä ovat saattaneet muuttaa string namea, eli kun saan weeklyt kiinni niin korjaantuu 😉

**Comment by Vihru** [comment]
toivotaan juu! :)
