### ISSUE TITLE
MiuiScreenRecorder.apk Recording Parameters

### ISSUE THREAD

**Issue by eeroah** [dogiex/MIUI-8.0-XML-FINNISH#44]
https://github.com/dogiex/MIUI-8.0-XML-FINNISH/blob/master/Finnish/main/MiuiScreenRecorder.apk/res/values-fi-rFI/strings.xml#L53

![image](https://cloud.githubusercontent.com/assets/16592874/26500619/34ee1eea-423f-11e7-870d-861d58afc15f.png)

Unohtunut vissiin siivota englannin kieli pois ko. riviltä.

**Comment by dogiex** [comment]
Jees näin on päässyt käymään. 😂
