### ISSUE TITLE
Lukitusnäytön lataushommelit on enkuksi vielä

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#47]
![screenshot_2017-05-27-15-19-41-895_lockscreen](https://cloud.githubusercontent.com/assets/24968370/26522397/574aee68-4308-11e7-8482-3628977b17f8.png)

**Comment by Vihru** [comment]
Jos viitsit mainita mikä versio / weekly sekä missä laitteessa ongelma ilmenee..

**Comment by dogiex** [comment]
Tuo päivitys tuli versiossa 7.5.25, kun kerkiän edelliset tehdä niin se kääntyy kanssa. Päivityshistorian näkee changelogista.
Olen siis hieman jäljessä, mutta en paljoa. Kiitos palautteesta ja jatkossa pyytäisin myös kertomaan ilmoituksessa laitteen nimen sekä miui version esim 7.5.25.

**Comment by Timbets** [comment]
juuh siis 7.5.25 redmi 4 prime
