### ISSUE TITLE
com.android.deskclock -> herätykseen minutes

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#49]
Laitteena Mi6, sekä weekly 7.5.25, herätykseen minutes?
![com android deskclock](https://user-images.githubusercontent.com/16348370/26880474-3a9268bc-4b9d-11e7-8215-923ea26e1980.jpg)

**Comment by dogiex** [comment]
Minulla tuo on suomeksi kyllä laitteissa Kate ja Cancro.

**Comment by Vihru** [comment]
mitenköhän on mahdollista ettei sitten oo tässä Mi6:ssa? _

**Comment by dogiex** [comment]
Ihmetellään sitä kun uusi weekly tulee jos vielä sama ongelma jatkuu

**Comment by dogiex** [comment]
Ilmeneekö sama ongelma weekly 7.6.8?

**Comment by Vihru** [comment]
herätykseen 23 tuntia 59 minuuttia, eli ongelma poistunut, voi sulkea minun puolesta.
