### ISSUE TITLE
com.android.camera -> pystykuva-tila

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#50]
Weekly 7.6.8, laitteena Mi6.  Kun avaa kameran ensimmäistä kertaa tulee ilmoitus pystykuva-tilasta.
Siinä tekstiä englanniksi. Muuten weekly vaikuttaa nopeasti katsottuna todella hyvältä.. englantia ei paljoa ole missään...  iso kiitos sinulle taas tässä välissä! 
![screenshot_2017-06-09-09-23-37-274_com android camera](https://user-images.githubusercontent.com/16348370/26964043-77f574fe-4cf8-11e7-82c5-ed98de371978.png)

**Comment by dogiex** [comment]
Minkälainen toi portrait mode on kamerassa?
Meinaan onko käännös oikein kun en oikein tiedä onko se pystykuva vai tyyliin taulu/muotokuva? Itellä ei ole tuota. Voitko demota tyyliin näytön nauhoituksella jos jaksat? :)

**Comment by Vihru** [comment]
tuo portrait mode on sellanen että se sumentaa taustan..  mikä nimitys tälle sit onkaan? kun paina tuosta portrait modesta, tulee teksti että stereo-tila auttaa sinua hämärtämään taustan? kohde ei saa olle pidemmällä, kuin 2 metriä?

**Comment by dogiex** [comment]
Ok, jätetään toistaiseksi tuo Pystykuva-tilaksi, voisi sen kait muuttaa Muotokuvaksi myös tai jotain vastaavaksi, jos joku hyvä termi sille löytyy. :)

**Comment by dogiex** [comment]
Ja toi Stereo on käännetty väärin, korjaan sen nyt.

**Comment by dogiex** [comment]
Korjaan käännöksen Muotokuvaksi.
