### ISSUE TITLE
Mobiili hotspotti

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#51]
7.5.25 redmi 4 prime
Omaan makuun vähän tökkii tuo "ei käytössä"
Parempi voisi olla "poista käytöstä" tai "lopeta" tai jotain muuta kuin ei käytössä. Nappi siis lopettaa jakamisen.
![image](https://user-images.githubusercontent.com/24968370/27095874-e71fb272-5077-11e7-8859-1b0d2acc1caf.png)

**Comment by dogiex** [comment]
Joo totta, kyseessä wifi hotspot jako?

**Comment by Timbets** [comment]
Jep, ja tuossa kuvan tilanteessa jako on siis täydessä käynnissä tabletille, eli ei ole mikään status tilanne käytössä/eikäytössä

**Comment by dogiex** [comment]
Kiitos. Pistetään korjaukseen. :)
