### ISSUE TITLE
com.android.settings -> datan käyttö

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#52]
Laitteena Xiaomi Mi6, Weekly-versio 7.6.15. Katso punaisella merkityt kohdat.
![screenshot_1970-03-24-17-37-32-430_com android settings](https://user-images.githubusercontent.com/16348370/27223224-41f2f7fa-5298-11e7-9e76-a5c4074ad460.png)

**Comment by dogiex** [comment]
Muutin myös "datan käytön raja" käännöksen "tiedonsiirtorajaksi".
