### ISSUE TITLE
com.android.settings -> wifi -> yhdistämisen tila

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#64]
Weekly 7.6.22, laitteena Mi6. Katso punaisella merkatut kohdat.
![screenshot_2017-06-25-19-30-31-172_com android settings](https://user-images.githubusercontent.com/16348370/27517954-b93f26d4-59dd-11e7-9fbc-d2b3a356ba0e.png)

**Comment by Vihru** [comment]
Tämä ongelma vieläkin laitteessa Mi6, weeklynä 7.6.29

**Comment by Vihru** [comment]
selviääkö tämä? :p

**Comment by dogiex** [comment]
Missä yhteydessä tämä valikko tulee esiin?
En ole niitä kääntänyt, koska en saa selvää yhteyttä mihin liittyvät, muuta kuin Wi-Fi yhdistämiseen ja muutenkin tuo comtible mode on todennäköisesti compatible mode, joten olen odottanut ns. kirjoitusvirheen korjausta xiaomin päästä, jotta tiedän tarkan käännöksen.

Mutta jos nuo ovat Compatible mode ja High mode niin miksi käännettäisiin?
- Yhteensopiva tila
- Korkea tila
?

Tuo korkea tila kyllä kuulostaa hieman tyhmältä, kun en tiedä mitä tuolla tehdään, koska en itse saa päivityksiä laitteelleni, kun vasta elokuussa.

**Comment by Vihru** [comment]
Hei, en minäkään muuta tiedä kun että WIFI-yhteden yhteensopivuustilaan jollain tavalla.. että käyttääkö se jonkinlaista yhteensopivuus tilaa yhdistäessä wifi-verkkoon jotta ongelmilta vältyttäisiin ja sitten tuo high mode taas ikäänku normaali tila..  ei tuolla nyt sellaista kiirettä ole..

**Comment by Vihru** [comment]
kiitos taas, oot tehny käännöksiä kaikenaikaa.. pian sitten tulee MIUI9, saa nähdä millanen se on tarkalleen..   tämä issue vähän epäselvä vielä? tuo mi remote ei myöskää oo muuttunu miksikään..

**Comment by Vihru** [comment]
tämä edelleen mi6 laitteessa, weeklynä 7.7.20..

**Comment by dogiex** [comment]
Viimeinen MIUI 8 versio oli 7.7.20.
Tämän johdosta tämä käännösprojekti jääköön unholaan ja tulkoon uusi projekti MIUI 9!
Uuden projektisivun löydät:

https://github.com/dogiex/MA-XML-9.0-FINNISH
