### ISSUE TITLE
com.android.mms -> nopeat vastaukset

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#65]
Weekly 7.6.22, laitteena Mi6. Katso punaisella merkatut kohdat.
![screenshot_2017-06-25-19-44-54-985_com android mms](https://user-images.githubusercontent.com/16348370/27518124-123df398-59e1-11e7-8e78-4da58a62e043.png)

**Comment by dogiex** [comment]
@ingbrzy Is there a translation strings available for Messages App Quick Responses?
I did a search query in XML compare folder and did not find those translations.

**Comment by ingbrzy** [comment]
Mms.apk/res/raw-fi/sms_frequently_used_phrase

`In a meeting, will call you later.

Sorry, I'm driving at the moment and will call you later.

Please call me later.`

**Comment by dogiex** [comment]
Thanks as always! 👍
