### ISSUE TITLE
com.miui.securitycenter-> punaisen kirjekuoren avustaja?

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#67]
Weekly 7.6.22, laitteena Mi6. Katso punaisella merkatut kohdat. eikös tuo ole se gamebooster tai vastaava?
![screenshot_2017-06-25-19-47-43-137_com miui securitycenter](https://user-images.githubusercontent.com/16348370/27518137-4c502042-59e1-11e7-82b3-cfea83c3ddee.png)

**Comment by dogiex** [comment]
Gameboosterin logo tuo on kyllä. Avaako kyseinen painike gameboosterin mukamas?

**Comment by Vihru** [comment]
avaa juu pelien nopeuttajan :)

**Comment by dogiex** [comment]
Kokeiletko vaihtaa englanniksi ja kertoa, näkyykö siinä Red envelope assistant vai Gamebooster teksti?

**Comment by Vihru** [comment]
![screenshot_2017-06-25-20-24-37-236_com miui securitycenter](https://user-images.githubusercontent.com/16348370/27518260-75c241b4-59e4-11e7-90dd-ae0472c54a9c.png)

**Comment by dogiex** [comment]
Mielenkiintoista...

**Comment by dogiex** [comment]
Tullut ilmeisesti buildaamisessa virhe, koska tuo Punaisen kirjekuoren avustaja on sama käännös stringi, kuin englannin pohjassa. Samoin Gamebooster käännöksen kanssa.

**Comment by Vihru** [comment]
mä yritin ettiä missä buildissa oli joku ilmotus että se olis tullu sen paikalle mutta en nyt äkkiseltää löytänyt..  ku muistan että joku semmonen info oli..

**Comment by dogiex** [comment]
Tarkistanpa uudelleen siis 😂

**Comment by Vihru** [comment]
löytyhän se!!
https://xiaomi.eu/community/threads/7-6-15.40462/page-10#post-373405

**Comment by dogiex** [comment]
Juu tuo pitäisi olla sisäinen koodaus, silti käännös pitäisi olla oikein, eli siinä pitäisi lukea Pelien nopeuttaja.

**Comment by dogiex** [comment]
@ingbrzy Gaming speed boost is getting wrong translation from Finnish strings in Security App.
It is showing wrong (Red envelope assistant) text instead of the correct translation. Strings are correct.

**Comment by ingbrzy** [comment]
`  <string name="card_main_hbassistant_summary">Boost speed and improve gaming experience</string>
   <string name="card_main_hbassistant_title">Gaming speed boost</string>`

**Comment by dogiex** [comment]
Thanks. Will fix this.
