### ISSUE TITLE
Kellon suomennos puuttuu (tunnit ja minuutit)

### ISSUE THREAD

**Issue by Tppap** [dogiex/MIUI-8.0-XML-FINNISH#69]
Ei mikää paha vika, en edes aluksi huomannut.. Mutta ajattelin ilmoittaa, että kun vaihdoin viimesimpään stable mikä mahdollista saada RN3 (hennesy).

**Comment by dogiex** [comment]
Viimeisin stable on aika vanha Hennesy laitteelle, joten ei ihme. Se on kuukausia vanha jo. Se on korjattu kyllä jo seuraavassa. ;)

**Comment by Tppap** [comment]
Joo se on vanha, toivottavasti joskus uus tulee :D mutta kiva tietää! En
ollut edes varma oliko edellisessä versiossa samalla tavalla :D

20.7.2017 18.06 "Dogiex" <notifications@github.com> kirjoitti:

**Comment by dogiex** [comment]
Eiköhän se 8.5 versio kohta tule, kun muut laitteet kanssa sen saanut. Jopa Redmi Note 2 :)
