### ISSUE TITLE
Asetukset -> Matkapuhelinverkot

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#7]
Kun asetuksista menee matkapuhelinverkot kohtaan niin sen jälkeen siellä on englanniksi tekstit.  Puhelimena Redmi 4 ja uusin weekly käytössä. 
![screenshot_2017-04-09-14-07-34-983_com android phone](https://cloud.githubusercontent.com/assets/16348370/24836795/2bcdaffa-1d2e-11e7-8cfd-db83c46753dd.png)
![screenshot_2017-04-09-14-07-42-581_com android phone](https://cloud.githubusercontent.com/assets/16348370/24836796/2dc9f660-1d2e-11e7-8b4a-9681d1d70f03.png)

**Comment by dogiex** [comment]
Kohdat ovat jo käännettynä. Weekly versio nähtävästi korvannut ne englannilla.

**Comment by Vihru** [comment]
eli ongelma ei ole sun käännöksissä vaan weeklyn muodostumisessa? pitäskö tuosta sanoa taas inbryzlle? Vai meinaatko että korjaantuu seuraavaan weeklyyn?

**Comment by dogiex** [comment]
Juuri näin. Edellisessä viestissä ingbrzy sanoi että selvittelee missä vika voisi olla, eiköhän se seuraavassa weeklyssä tule taas suomeksi

**Comment by dogiex** [comment]
Mutta toivottavasti tämä ongelma ratkeisi, minkä takia välillä käännökset kääntyy takaisin englanniksi itsekseen ja taas takaisin suomeksi seuraavissa päivityksissä.

**Comment by Vihru** [comment]
pitäskö ingryzltä kysyä onko se löytänyt syytä ongelmaan tai ratkaisua?  ni huomais että meitä on täällä oikeesti ketkä haluaa suomenkielen saada toimiin kunnolla.

**Comment by dogiex** [comment]
Kysy pois. 😁

**Comment by Vihru** [comment]
juu laitoin sille viestiä :p katotaan mitä vastaa.

**Comment by Vihru** [comment]
huomasin että tässä mi5 ei oo samoja käännös ongelmia ku redmi 4 prossa.. ingbrzy lupas kattoo mikä mättää.

**Comment by dogiex** [comment]
Jep sitä tarkoitinkin. Mulla Katessa kaikki käännökset toimivat tällä hetkellä.

**Comment by Vihru** [comment]
Onko Mi remote käännetty? se ainaki mi5:ssa vielä enkuks.. ääninauhurissa ois yks kohta.. eli siinä napin alapuolella lukee nauhoitetaan vaikka nauhoitus ei oliskaan päällä? voisko sen muuttaa että nauhoita?
![screenshot_2017-04-10-18-18-46-733_com android soundrecorder](https://cloud.githubusercontent.com/assets/16348370/24869756/e91add8c-1e1c-11e7-9f54-04a8d45b6fa9.png)

**Comment by Vihru** [comment]
ingrbzy laitto mulle uuden buildin tähä redml 4 primeen ja se korjas ongelmat ! :)

**Comment by dogiex** [comment]
Mi Remotea olen hieman kääntänyt, samoin videosoitinta, ne kaksi on vielä kääntämättä, mutta nähtävästi remotessa ei ole niitä käännöksiä ollenkaan. Joo nähtävästi tullut hieman väärä käännös tohon nappulaan. Korjaan sen.
