### ISSUE TITLE
Spell checker

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#71]
Redmi Note 4 (Mido)
7.7.13
oikoluku englanniksi vielä

![image](https://user-images.githubusercontent.com/24968370/28493738-56e5cf86-6f24-11e7-982f-1dfb50828557.png)

(Myös kello on tunnin väärässä, en toki ole käyttänyt Simia vielä ,mutta kai sen pitäisi kesäajat ymmärtää ilmankin?)

**Comment by dogiex** [comment]
Oletko tarkistanut aikavyöhykkeen asetuksen?
Se pitäisi päivittyä verkon mukaan automaattisesti tai käsin.

**Comment by dogiex** [comment]
Voitko @vihru tarkistaa onko Mi 6 laitteessasi oikeinkirjoitus käännetty? :)

**Comment by Timbets** [comment]
Jep, todennäköisesti SIM kortin käyttö laitteessa korjaisi tuon, mutta
todennäköisesti tämän alkuasennuksen suomen kielen valinnan jälkeen aikavyöhyke on virheellisesti keskieuroopan aika. 
![image](https://user-images.githubusercontent.com/24968370/28494297-8dcb52f6-6f32-11e7-819e-7adb2d759b4f.png)

**Comment by dogiex** [comment]
Kokeiletko ottaa automatiikan pois, valita helsingin ja sen jälkeen automatiikka takaisin päälle?

**Comment by Timbets** [comment]
Se näytti pysyvän oikeana tuon manuaalimuutoksen jälkeen

**Comment by Vihru** [comment]
Default spell checker lukee eli samalla tavalla kun timbetsillä. laitteena Mi6, weekly 7.7.20. kello-ongelmaa ei minulla ainakaan sim-kortin kanssa.

**Comment by dogiex** [comment]
Kiitos @Vihru.
Pistetään korjaukseen :)
