### ISSUE TITLE
Lukitusnäyttö pikakuvake

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#72]
RN4 Mido
7.7.13

Asetin vasemmalla pikakuvakkeen Puhehaulle. Lukee silti Mi kaukosäädin. Enkuksi toimii. 
![image](https://user-images.githubusercontent.com/24968370/28495490-16294e72-6f57-11e7-86ef-d1824586dd30.png)

**Comment by dogiex** [comment]
Oletko laittanut google sovelluksen muistiin lukkoon?

**Comment by Timbets** [comment]
Juu on, olikin väärä hälytys tuo puhehaun toimimattomuus. Oli unohtunut lukitus vielä päälle. Alkuvuodesta oli vielä bugi (redmi 4 prime sillloin),  jossa tuo puhehaku ei voinut asettaa esim ajastinta "koska laite on lukittuna", vaikka laitteessa ei ollut mitään lukitusta käytössä. Nyt tuo on korjattu ainakin tässä Midossa.

Mutta siis itse käännösvirhe on. eli mitä tahansa tuohon laittaa pikakuvakeohjelmaksi niin siinä lukee Mi kaukosäädin. Englanniksi toimii oikein eli ohjelman nimi vaihtuu.

**Comment by dogiex** [comment]
Mido päivitty nyt 7.7.20 versioon eli se on nyt saatavilla, kokeileppas vielä sillä. :)

**Comment by Timbets** [comment]
Jep sama vika, kokeilin kellolla tällä kertaa. Edelleen luki Mi kaukosäädin.

**Comment by dogiex** [comment]
Ok kiitos tiedosta. Tarkistetaan asia.

**Comment by dogiex** [comment]
Korjaan asian seuraavaan weeklyyn. :)

**Comment by Timbets** [comment]
Ei kiirettä, vahingossa vain huomasin tuon.
Onkohan toisella puolella sama? En uskaltanut testata toimiko se kameran puoli kun en tiedä saisiko enää samaa ikonia takaisin. Ainakin tuonne vasemmalle puolelle tuli eri kamera ikoni kun sinnekin lisäsi kameran.

Mahtaakohan seuraava nightly olla vielä MIUI9, ainakin ekojen joukossa kai tämä mido

**Comment by dogiex** [comment]
Joo toisella puolella on sama vika. Korjaan käännösvirheen myös siihen. :)
Kyllä se MIUI 9 sieltä tulee, saat sen ekojen joukossa. 😎

**Comment by dogiex** [comment]
@Timbets voisitko tarkistaa toimiiko sulla kehittäjäasetukset ?

**Comment by Timbets** [comment]
toimii
https://dl2.pushbulletusercontent.com/ikfhkizGUhyWnN32UMBWsah4evkTz1UT/Screenshot_2017-07-24-07-55-15-591_com.android.settings.png

**Comment by dogiex** [comment]
Hienoa mahtavaa
