### ISSUE TITLE
Hotspotti

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#73]
RN4 mido
7.7.20

"Ei mitään kannettava" voisi olla vaikka ei kannettaava hotspottia tai jotain
![image](https://user-images.githubusercontent.com/24968370/28572777-0dfafe3e-7151-11e7-8574-25f7ae5fdaad.png)
![image](https://user-images.githubusercontent.com/24968370/28572780-13d9ae7c-7151-11e7-8b02-a1fd52b5d533.png)

**Comment by dogiex** [comment]
Korjattu seuraavaan versioon.
