### ISSUE TITLE
Käyttäjät

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#75]
RN4 mido
7.7.20
Aetukset-Käyttäjät
![image](https://user-images.githubusercontent.com/24968370/28572932-8eacf15e-7151-11e7-823f-b411eaa10985.png)

**Comment by Timbets** [comment]
Tuo Emergency information ei taida tosin MIUIssa toimia. Tuon avatessa antaa englanninkielisen info popupin vielä.

**Comment by dogiex** [comment]
Otappa kuvakaappaus siitä ponnahdusikkunasta?

**Comment by Timbets** [comment]
Tuli vain ensimmäisellä kerralla, joten en saa sitä enää näkyviin :/

**Comment by dogiex** [comment]
Ai, no ei se mitään. Muistaakseni käänsin noi jo, mutta jätetään tämä avoimeksi vielä, jos tämän tarkistaisi sitten seuraavalla weekly versiolla, kun tulee ulos.

**Comment by Timbets** [comment]
Tuossa valmiiksi käännettynä sama popup Lineagesta. Tuo olis siis enkuksi vielä Miuissa.
![image](https://user-images.githubusercontent.com/24968370/28573381-25e7c0ca-7153-11e7-985c-cf5a71d3b32d.png)

**Comment by dogiex** [comment]
Kiitos paljon. :)

**Comment by dogiex** [comment]
Korjattu seuraavaan versioon.
