### ISSUE TITLE
Tiedostoselaimen kautta videota

### ISSUE THREAD

**Issue by Timbets** [dogiex/MIUI-8.0-XML-FINNISH#76]
RN4 mido 7.7.20
Laitoin tiedostoselaimen kautta videota pyörimään. ilmoitti enkuksi jotain ja poismennessä enkuksi toasti.
https://dl2.pushbulletusercontent.com/nx5WjKzcHHJMLUPWq15tpKshHm9JCuY3/Screenshot_2017-07-26-18-22-28-526_com.miui.video.png

**Comment by dogiex** [comment]
Viimeinen MIUI 8 versio oli 7.7.20.
Tämän johdosta tämä käännösprojekti jääköön unholaan ja tulkoon uusi projekti MIUI 9!
Uuden projektisivun löydät:
https://github.com/dogiex/MA-XML-9.0-FINNISH

**Comment by dogiex** [comment]
P.s. Videosoitin uusiutuu MIUI 9:ssä, joten älä suotta tee vielä uuteen käännösprojektiin tätä samaa ilmoitusta. :)
