### ISSUE TITLE
Asetukset -> Mi Tili

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#8]
Kun asetuksista menee Mi Tili kohtaan niin sen jälkeen siellä on englanniksi tekstit.  Puhelimena Redmi 4 ja uusin weekly käytössä. 
![screenshot_2017-04-09-14-12-22-897_com xiaomi account](https://cloud.githubusercontent.com/assets/16348370/24836820/fc5a2c48-1d2e-11e7-9ae5-846b972dff6f.png)

**Comment by dogiex** [comment]
Kohdat ovat jo käännettynä. Weekly versio nähtävästi korvannut ne englannilla.
