### ISSUE TITLE
Asetukset -> Järjestelmäsovellukset

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#9]
Kun asetuksista menee järjestelmäsovellukset kohtaan niin sen jälkeen siellä on PHONE sekä RECORDER kohdat englanniksi. Puhelimena Redmi 4 ja uusin weekly käytössä. 
![screenshot_2017-04-09-14-12-59-161_com android settings](https://cloud.githubusercontent.com/assets/16348370/24836829/259b5078-1d2f-11e7-90b2-92ab4d1905c1.png)

**Comment by dogiex** [comment]
Kohdat ovat jo käännettynä. Weekly versio nähtävästi korvannut ne englannilla.
